CREATE TABLE UTILISATEUR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PSEUDO VARCHAR(255) NOT NULL,
    NOM VARCHAR(255) NOT NULL,
    PRENOM VARCHAR(255) NOT NULL,
    BIRTHDAY DATE,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    TEL VARCHAR(255),
    ADRESS VARCHAR(255),
    CP VARCHAR(10),
    VILLE VARCHAR(255),
    NUMADRESSE VARCHAR(10),
    GENRE  VARCHAR(255)
);

CREATE TABLE CAGNOTTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDUSER INT,
    NOM VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    OBJECTIF INT NOT NULL,
    ETAT VARCHAR(255) NOT NULL,
    DATEDEBUT DATE,
    DATEFIN DATE,
    IMAGEURL VARCHAR(255),
    FOREIGN KEY (IDUSER) REFERENCES UTILISATEUR(ID)
);

CREATE TABLE COMMENTAIRE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDUSER INT,
    IDCAGNOTTE INT,
    DATE  DATE,
    COMMENTAIRE VARCHAR (255),
    FOREIGN KEY (IDUSER) REFERENCES UTILISATEUR(ID),
    FOREIGN KEY (IDCAGNOTTE) REFERENCES CAGNOTTE(ID)
);

CREATE TABLE PARTICIPATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDCAGNOTTE INT,
    IDUSER INT,
    DATE_TIMESTAMP INT,
    PAIEMENT_TYPE VARCHAR(50),
    STATUT_PAIEMENT VARCHAR(15)NOT NULL,
    AMOUNT INT NOT NULL,
    FOREIGN KEY (IDCAGNOTTE) REFERENCES CAGNOTTE(ID),
    FOREIGN KEY (IDUSER) REFERENCES UTILISATEUR(ID)
); 
